Args = --enable-preview \
       --no-fallback \
       --allow-incomplete-classpath \
       --report-unsupported-elements-at-runtime \
       -H:+ReportExceptionStackTraces \
       -H:+AddAllCharsets \
       --enable-url-protocols=http,https \
       --initialize-at-build-time=org.slf4j.LoggerFactory \
       --initialize-at-build-time=org.slf4j.impl.StaticLoggerBinder \
       --initialize-at-build-time=ch.qos.logback \
       --initialize-at-run-time=io.netty.util.internal.logging.Log4JLogger \
       --initialize-at-run-time=io.netty.handler.ssl \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSsl \
       --initialize-at-run-time=io.netty.channel.DefaultChannelId \
       --initialize-at-run-time=io.netty.util.concurrent.DefaultPromise \
       --initialize-at-run-time=org.hibernate \
       --initialize-at-run-time=org.sqlite.JDBC
