apiVersion: skill.ooder.net/v1
kind: Skill

metadata:
  id: skill-org-feishu
  name: Feishu Organization Service
  version: 0.7.0
  description: Provides organization data integration with Feishu (Lark)
  author: ooder Team
  license: Apache-2.0
  homepage: https://gitee.com/ooderCN/skill-org-feishu
  keywords:
    - feishu
    - lark
    - organization
    - enterprise

spec:
  type: enterprise-skill
  
  runtime:
    language: java
    javaVersion: "8"
    framework: spring-boot
    mainClass: net.ooder.skill.org.feishu.FeishuSkillApplication
    jvmOpts: "-Xms256m -Xmx512m"
  
  capabilities:
    - id: org-data-read
      name: Organization Data Read
      description: Read organization structure and member data from Feishu
      category: data-access
    - id: user-auth
      name: User Authentication
      description: Authenticate users via Feishu OAuth
      category: authentication
    - id: send-message
      name: Send Message
      description: Send messages to Feishu users or groups
      category: communication
  
  scenes:
    - name: auth
      description: Authentication scene with organization data support
      capabilities:
        - org-data-read
        - user-auth
      roles:
        - roleId: org-provider
          name: Organization Provider
          required: true
          capabilities: [org-data-read, user-auth]
      communicationProtocol: http
      securityPolicy: api-key
      allowParallel: true
    - name: messaging
      description: Unified messaging scene
      capabilities:
        - send-message
      roles:
        - roleId: msg-provider
          name: Message Provider
          required: true
          capabilities: [send-message]
      communicationProtocol: http
      securityPolicy: api-key
      allowParallel: false
  
  config:
    required:
      - name: FEISHU_APP_ID
        type: string
        description: Feishu application ID
        secret: false
      - name: FEISHU_APP_SECRET
        type: string
        description: Feishu application secret
        secret: true
    optional:
      - name: FEISHU_API_BASE_URL
        type: string
        default: https://open.feishu.cn/open-apis
        description: Feishu API base URL
      - name: FEISHU_BOT_NAME
        type: string
        default: ooder Bot
        description: Bot display name
  
  endpoints:
    - path: /api/org/tree
      method: GET
      description: Get organization tree
      capability: org-data-read
      authentication: true
    - path: /api/auth/verify
      method: POST
      description: Verify user authentication
      capability: user-auth
      authentication: false
    - path: /api/message/send
      method: POST
      description: Send message
      capability: send-message
      authentication: true
  
  resources:
    cpu: "500m"
    memory: "512Mi"
    storage: "1Gi"
  
  deployment:
    modes:
      - remote-hosted
      - local-deployed
    singleton: true
    requiresAuth: true
    healthCheck:
      path: /actuator/health
      interval: 30
      timeout: 10
