package net.ooder.skillcenter.ide;

import java.util.Map;

/**
 * 代码生成插件，用于生成各种编程语言的代码
 */
public class CodeGenerationPlugin implements IDEPlugin {
    private boolean available;
    
    @Override
    public String getPluginId() {
        return "code-generation-plugin";
    }
    
    @Override
    public String getPluginName() {
        return "Code Generation Plugin";
    }
    
    @Override
    public String getDescription() {
        return "Generates code in various programming languages based on prompts";
    }
    
    @Override
    public void start() {
        available = true;
        System.out.println("Code Generation Plugin started");
    }
    
    @Override
    public void stop() {
        available = false;
        System.out.println("Code Generation Plugin stopped");
    }
    
    @Override
    public boolean isAvailable() {
        return available;
    }
    
    /**
     * 生成代码
     * @param language 编程语言
     * @param prompt 代码生成提示
     * @param context 生成上下文
     * @return 生成的代码
     */
    public String generateCode(String language, String prompt, Map<String, Object> context) {
        if (!available) {
            return "// Code generation plugin is not available";
        }
        
        System.out.println("Generating code in " + language + " for prompt: " + prompt);
        
        // 模拟代码生成
        return generateMockCode(language, prompt, context);
    }
    
    /**
     * 生成模拟代码
     */
    private String generateMockCode(String language, String prompt, Map<String, Object> context) {
        switch (language.toLowerCase()) {
            case "java":
                return generateJavaCode(prompt, context);
            case "python":
                return generatePythonCode(prompt, context);
            case "javascript":
            case "js":
                return generateJavaScriptCode(prompt, context);
            case "typescript":
            case "ts":
                return generateTypeScriptCode(prompt, context);
            case "csharp":
            case "c#":
                return generateCSharpCode(prompt, context);
            case "cpp":
            case "c++":
                return generateCppCode(prompt, context);
            default:
                return String.format("// Generated code for %s\n// Prompt: %s", language, prompt);
        }
    }
    
    /**
     * 生成Java代码
     */
    private String generateJavaCode(String prompt, Map<String, Object> context) {
        return "// Java code generated by AI-IDE\n" +
               "public class GeneratedClass {\n" +
               "    public static void main(String[] args) {\n" +
               "        System.out.println(\"Generated Java code for prompt: \" + \"" + prompt + "\");\n" +
               "    }\n" +
               "}\n";
    }
    
    /**
     * 生成Python代码
     */
    private String generatePythonCode(String prompt, Map<String, Object> context) {
        return "# Python code generated by AI-IDE\n" +
               "def main():\n" +
               "    print('Generated Python code for prompt: " + prompt + "')\n" +
               "\n" +
               "if __name__ == '__main__':\n" +
               "    main()\n";
    }
    
    /**
     * 生成JavaScript代码
     */
    private String generateJavaScriptCode(String prompt, Map<String, Object> context) {
        return "// JavaScript code generated by AI-IDE\n" +
               "function main() {\n" +
               "    console.log('Generated JavaScript code for prompt: " + prompt + "');\n" +
               "}\n" +
               "\n" +
               "main();\n";
    }
    
    /**
     * 生成TypeScript代码
     */
    private String generateTypeScriptCode(String prompt, Map<String, Object> context) {
        return "// TypeScript code generated by AI-IDE\n" +
               "function main(): void {\n" +
               "    console.log('Generated TypeScript code for prompt: " + prompt + "');\n" +
               "}\n" +
               "\n" +
               "main();\n";
    }
    
    /**
     * 生成C#代码
     */
    private String generateCSharpCode(String prompt, Map<String, Object> context) {
        return "// C# code generated by AI-IDE\n" +
               "using System;\n" +
               "\n" +
               "class Program\n" +
               "{\n" +
               "    static void Main()\n" +
               "    {\n" +
               "        Console.WriteLine('Generated C# code for prompt: " + prompt + "');\n" +
               "    }\n" +
               "}\n";
    }
    
    /**
     * 生成C++代码
     */
    private String generateCppCode(String prompt, Map<String, Object> context) {
        StringBuilder code = new StringBuilder();
        code.append("// C++ code generated by AI-IDE\n");
        code.append("#include <iostream>\n");
        code.append("\n");
        code.append("int main() {\n");
        code.append("    std::cout << \"Generated C++ code for prompt: ");
        code.append(prompt);
        code.append("\" << std::endl;\n");
        code.append("    return 0;\n");
        code.append("}\n");
        return code.toString();
    }
}