{
  "alias": "DatePicker",
  "children": [
    {
      "alias": "PAGECTX",
      "children": [
        {
          "alias": "fieldname",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.form.field.datetime.DatePicker.PAGECTX.fieldname",
          "properties": {
            "formField": true,
            "isPid": true,
            "name": "fieldname",
            "pid": true,
            "tabindex": 0
          }
        },
        {
          "alias": "currentClassName",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.form.field.datetime.DatePicker.PAGECTX.currentClassName",
          "properties": {
            "formField": true,
            "isPid": true,
            "name": "currentClassName",
            "pid": true,
            "tabindex": 1
          }
        },
        {
          "alias": "xpath",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.form.field.datetime.DatePicker.PAGECTX.xpath",
          "properties": {
            "formField": true,
            "isPid": true,
            "name": "xpath",
            "pid": true,
            "tabindex": 2
          }
        },
        {
          "alias": "sourceMethodName",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.form.field.datetime.DatePicker.PAGECTX.sourceMethodName",
          "properties": {
            "formField": true,
            "isPid": true,
            "name": "sourceMethodName",
            "pid": true,
            "tabindex": 3
          }
        },
        {
          "alias": "sourceClassName",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.form.field.datetime.DatePicker.PAGECTX.sourceClassName",
          "properties": {
            "formField": true,
            "isPid": true,
            "name": "sourceClassName",
            "pid": true,
            "tabindex": 4
          }
        },
        {
          "alias": "methodName",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.form.field.datetime.DatePicker.PAGECTX.methodName",
          "properties": {
            "formField": true,
            "isPid": false,
            "name": "methodName",
            "pid": false,
            "tabindex": 5
          }
        },
        {
          "alias": "projectName",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.form.field.datetime.DatePicker.PAGECTX.projectName",
          "properties": {
            "formField": true,
            "isPid": false,
            "name": "projectName",
            "pid": false,
            "tabindex": 6,
            "value": "DSMdsmVVVERSION0"
          }
        },
        {
          "alias": "domainId",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.form.field.datetime.DatePicker.PAGECTX.domainId",
          "properties": {
            "formField": true,
            "isPid": true,
            "name": "domainId",
            "pid": true,
            "tabindex": 7
          }
        },
        {
          "alias": "projectVersionName",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.form.field.datetime.DatePicker.PAGECTX.projectVersionName",
          "properties": {
            "formField": true,
            "isPid": false,
            "name": "projectVersionName",
            "pid": false,
            "tabindex": 8,
            "value": "DSMdsmVVVERSION0"
          }
        },
        {
          "alias": "viewClassName",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.form.field.datetime.DatePicker.PAGECTX.viewClassName",
          "properties": {
            "formField": true,
            "isPid": true,
            "name": "viewClassName",
            "pid": true,
            "tabindex": 9
          }
        }
      ],
      "events": {},
      "key": "ood.UI.Block",
      "params": {},
      "path": "dsm.view.config.form.field.datetime.DatePicker.PAGECTX",
      "properties": {
        "borderType": "none",
        "tabindex": 0,
        "visibility": "hidden"
      }
    },
    {
      "alias": "DatePickerMain",
      "children": [
        {
          "alias": "DatePicker",
          "children": [
            {
              "alias": "fieldname",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.form.field.datetime.DatePicker.DatePickerMain.DatePicker.fieldname",
              "properties": {
                "caption": "字段名",
                "defaultFocus": false,
                "desc": "字段名",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "fieldname",
                "imageClass": "",
                "items": [],
                "labelCaption": "字段名",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "fieldname",
                "readonly": true,
                "tabindex": 0,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "B1"
            },
            {
              "alias": "height",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.form.field.datetime.DatePicker.DatePickerMain.DatePicker.height",
              "properties": {
                "caption": "高度",
                "defaultFocus": false,
                "desc": "高度",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "height",
                "imageClass": "",
                "items": [],
                "labelCaption": "高度",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "height",
                "readonly": false,
                "tabindex": 1,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "D1"
            },
            {
              "alias": "width",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.form.field.datetime.DatePicker.DatePickerMain.DatePicker.width",
              "properties": {
                "caption": "宽度",
                "defaultFocus": false,
                "desc": "宽度",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "width",
                "imageClass": "",
                "items": [],
                "labelCaption": "宽度",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "width",
                "readonly": false,
                "tabindex": 2,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "B2"
            },
            {
              "alias": "value",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.form.field.datetime.DatePicker.DatePickerMain.DatePicker.value",
              "properties": {
                "caption": "默认值",
                "defaultFocus": false,
                "desc": "默认值",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "value",
                "imageClass": "",
                "items": [],
                "labelCaption": "默认值",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "value",
                "readonly": false,
                "tabindex": 3,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "D2"
            },
            {
              "alias": "closeBtn",
              "events": {},
              "key": "ood.UI.CheckBox",
              "path": "dsm.view.config.form.field.datetime.DatePicker.DatePickerMain.DatePicker.closeBtn",
              "properties": {
                "caption": "",
                "defaultFocus": false,
                "desc": "关闭按钮",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "dock": "none",
                "events": {},
                "id": "closeBtn",
                "name": "closeBtn",
                "tabindex": 4,
                "visibility": "visible"
              },
              "target": "B3"
            },
            {
              "alias": "timeInput",
              "events": {},
              "key": "ood.UI.CheckBox",
              "path": "dsm.view.config.form.field.datetime.DatePicker.DatePickerMain.DatePicker.timeInput",
              "properties": {
                "caption": "",
                "defaultFocus": false,
                "desc": "显示时间",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "dock": "none",
                "events": {},
                "id": "timeInput",
                "name": "timeInput",
                "tabindex": 5,
                "visibility": "visible"
              },
              "target": "D3"
            },
            {
              "alias": "firstDayOfWeek",
              "events": {},
              "key": "ood.UI.ComboInput",
              "path": "dsm.view.config.form.field.datetime.DatePicker.DatePickerMain.DatePicker.firstDayOfWeek",
              "properties": {
                "caption": "第一天",
                "currencyTpl": "$ *",
                "decimalSeparator": ".",
                "defaultFocus": false,
                "desc": "第一天",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "forceFillZero": true,
                "increment": 1,
                "items": [],
                "labelCaption": "第一天",
                "name": "firstDayOfWeek",
                "precision": 0,
                "readonly": false,
                "tabindex": 6,
                "type": "number",
                "visibility": "visible"
              },
              "target": "B4"
            },
            {
              "alias": "offDays",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.form.field.datetime.DatePicker.DatePickerMain.DatePicker.offDays",
              "properties": {
                "caption": "下一天",
                "defaultFocus": false,
                "desc": "下一天",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "offDays",
                "imageClass": "",
                "items": [],
                "labelCaption": "下一天",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "offDays",
                "readonly": false,
                "tabindex": 7,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "D4"
            },
            {
              "alias": "hideWeekLabels",
              "events": {},
              "key": "ood.UI.CheckBox",
              "path": "dsm.view.config.form.field.datetime.DatePicker.DatePickerMain.DatePicker.hideWeekLabels",
              "properties": {
                "caption": "",
                "defaultFocus": false,
                "desc": "隐藏周",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "dock": "none",
                "events": {},
                "id": "hideWeekLabels",
                "name": "hideWeekLabels",
                "tabindex": 8,
                "visibility": "visible"
              },
              "target": "B5"
            },
            {
              "alias": "dateInputFormat",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.form.field.datetime.DatePicker.DatePickerMain.DatePicker.dateInputFormat",
              "properties": {
                "caption": "日期格式",
                "defaultFocus": false,
                "desc": "日期格式",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "dateInputFormat",
                "imageClass": "",
                "items": [],
                "labelCaption": "日期格式",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "dateInputFormat",
                "readonly": false,
                "tabindex": 9,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "D5"
            }
          ],
          "events": {},
          "key": "ood.UI.FormLayout",
          "path": "dsm.view.config.form.field.datetime.DatePicker.DatePickerMain.DatePicker",
          "properties": {
            "caption": "日期选择框",
            "defaultColWidth": 150,
            "defaultColumnSize": -1,
            "defaultFocus": false,
            "defaultRowHeight": 35,
            "defaultRowSize": -1,
            "disableClickEffect": false,
            "disableHoverEffect": false,
            "disableTips": false,
            "disabled": false,
            "dock": "fill",
            "floatHandler": false,
            "id": "datePicker",
            "imageClass": "ri-calendar-line",
            "layoutData": {
              "cells": {
                "A1": {
                  "cellName": "A1",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "字段名"
                },
                "C3": {
                  "cellName": "C3",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "显示时间"
                },
                "A2": {
                  "cellName": "A2",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "宽度"
                },
                "C4": {
                  "cellName": "C4",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "下一天"
                },
                "A3": {
                  "cellName": "A3",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "关闭按钮"
                },
                "C5": {
                  "cellName": "C5",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "日期格式"
                },
                "A4": {
                  "cellName": "A4",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "第一天"
                },
                "A5": {
                  "cellName": "A5",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "隐藏周"
                },
                "C1": {
                  "cellName": "C1",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "高度"
                },
                "C2": {
                  "cellName": "C2",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "默认值"
                }
              },
              "colSetting": {
                "A": {
                  "manualWidth": 150
                },
                "B": {
                  "manualWidth": 150
                },
                "C": {
                  "manualWidth": 150
                },
                "D": {
                  "manualWidth": 150
                }
              },
              "cols": 4,
              "rowSetting": {
                "1": {
                  "manualHeight": 35
                },
                "2": {
                  "manualHeight": 35
                },
                "3": {
                  "manualHeight": 35
                },
                "4": {
                  "manualHeight": 35
                },
                "5": {
                  "manualHeight": 35
                }
              },
              "rows": 5
            },
            "lineSpacing": 10,
            "mode": "write",
            "name": "GetDatePicker",
            "solidGridlines": true,
            "stretchH": "all",
            "stretchHeight": "none",
            "tabindex": 0,
            "tagVar": {},
            "visibility": "visible"
          }
        },
        {
          "alias": "SAVEBottomBlock",
          "children": [
            {
              "alias": "SAVEBottom",
              "apis": [],
              "events": {
                "onClick": {
                  "actions": [
                    {
                      "args": [
                        "{page.RESET.invoke()}"
                      ],
                      "conditions": [
                        {
                          "symbol": "=",
                          "left": "{args[1].id}",
                          "right": "RESET_button"
                        }
                      ],
                      "desc": "重置",
                      "enumClassName": "net.ooder.esd.annotation.action.CustomFormAction",
                      "enumValue": "RESET",
                      "eventClass": "net.ooder.esd.annotation.event.FieldEventEnum",
                      "eventValue": "onClick",
                      "id": "net.ooder.esd.annotation.action.CustomFormAction_RESET_null_null",
                      "method": "invoke",
                      "redirection": "other:callback:call",
                      "return": false,
                      "target": "RESET",
                      "type": "control"
                    },
                    {
                      "args": [
                        "{page.SAVE.invoke()}"
                      ],
                      "conditions": [
                        {
                          "symbol": "=",
                          "left": "{args[1].id}",
                          "right": "SAVE_button"
                        }
                      ],
                      "desc": "保存",
                      "enumClassName": "net.ooder.esd.annotation.action.CustomFormAction",
                      "enumValue": "SAVE",
                      "eventClass": "net.ooder.esd.annotation.event.FieldEventEnum",
                      "eventValue": "onClick",
                      "id": "net.ooder.esd.annotation.action.CustomFormAction_SAVE_null_null",
                      "method": "invoke",
                      "redirection": "other:callback:call",
                      "return": true,
                      "target": "SAVE",
                      "type": "control"
                    }
                  ]
                }
              },
              "key": "ood.UI.StatusButtons",
              "menuType": "BOTTOMBAR",
              "path": "dsm.view.config.form.field.datetime.DatePicker.DatePickerMain.SAVEBottomBlock.SAVEBottom",
              "properties": {
                "borderType": "none",
                "dock": "fill",
                "itemType": "button",
                "itemWidth": "auto",
                "items": [
                  {
                    "caption": "重置",
                    "iconColor": "#E6945C",
                    "id": "RESET_button",
                    "imageClass": "ri-refresh-line",
                    "index": 0,
                    "itemType": "button",
                    "tabindex": 0,
                    "tagVar": {
                      "name": "RESET",
                      "clazz": "net.ooder.esd.annotation.menu.CustomFormMenu"
                    },
                    "tips": "重置",
                    "title": "重置"
                  },
                  {
                    "caption": "保存",
                    "iconColor": "#195ead",
                    "id": "SAVE_button",
                    "imageClass": "ri-save-line",
                    "index": 0,
                    "itemType": "button",
                    "tabindex": 1,
                    "tagVar": {
                      "name": "SAVE",
                      "clazz": "net.ooder.esd.annotation.menu.CustomFormMenu"
                    },
                    "tips": "保存",
                    "title": "保存"
                  }
                ],
                "menuType": "BOTTOMBAR",
                "position": "static",
                "showCaption": true,
                "tabindex": 0,
                "width": "auto"
              }
            }
          ],
          "events": {},
          "key": "ood.UI.Block",
          "path": "dsm.view.config.form.field.datetime.DatePicker.DatePickerMain.SAVEBottomBlock",
          "properties": {
            "borderType": "none",
            "comboType": "STATUSBUTTONS",
            "dock": "bottom",
            "height": "3.0em",
            "overflow": "hidden",
            "tabindex": 1
          }
        }
      ],
      "events": {},
      "key": "ood.UI.Block",
      "path": "dsm.view.config.form.field.datetime.DatePicker.DatePickerMain",
      "properties": {
        "dock": "fill",
        "panelBgClr": "transparent",
        "tabindex": 1
      }
    },
    {
      "alias": "SAVE",
      "events": {},
      "key": "ood.APICaller",
      "path": "dsm.view.config.form.field.datetime.DatePicker.SAVE",
      "properties": {
        "allform": false,
        "autoRun": false,
        "checkRequired": false,
        "checkValid": false,
        "desc": "保存",
        "id": "/dsm/view/config/form/field/combo/date/updateDatePicker",
        "imageClass": "ri-code-box-line",
        "isAllform": false,
        "methodName": "updateDatePicker",
        "name": "updateDatePicker",
        "proxyType": "auto",
        "queryAsync": true,
        "queryMethod": "POST",
        "queryURL": "/dsm/view/config/form/field/combo/date/updateDatePicker",
        "requestDataSource": [
          {
            "name": "comboView",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "projectName",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "domainId",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "comboView",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "projectName",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "domainId",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "DatePickerMain",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "PAGECTX",
            "path": "",
            "type": "FORM"
          }
        ],
        "requestType": "JSON",
        "responseCallback": [],
        "responseDataTarget": [],
        "responseType": "JSON",
        "sourceClassName": "net.ooder.dsm.view.config.form.field.combo.service.ComboDateService",
        "tabindex": 2,
        "tips": "保存"
      }
    },
    {
      "alias": "RESET",
      "events": {},
      "key": "ood.APICaller",
      "path": "dsm.view.config.form.field.datetime.DatePicker.RESET",
      "properties": {
        "allform": false,
        "autoRun": false,
        "checkRequired": false,
        "checkValid": false,
        "desc": "reSetDatePicker",
        "id": "/dsm/view/config/form/field/combo/date/reSetDatePicker",
        "imageClass": "ri-code-box-line",
        "isAllform": false,
        "methodName": "reSetDatePicker",
        "name": "reSetDatePicker",
        "proxyType": "auto",
        "queryAsync": true,
        "queryMethod": "POST",
        "queryURL": "/dsm/view/config/form/field/combo/date/reSetDatePicker",
        "requestDataSource": [
          {
            "name": "comboView",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "projectName",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "domainId",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "comboView",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "projectName",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "domainId",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "DatePickerMain",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "PAGECTX",
            "path": "",
            "type": "FORM"
          }
        ],
        "requestType": "JSON",
        "responseCallback": [],
        "responseDataTarget": [],
        "responseType": "JSON",
        "sourceClassName": "net.ooder.dsm.view.config.form.field.combo.service.ComboDateService",
        "tabindex": 3,
        "tips": "reSetDatePicker"
      }
    },
    {
      "alias": "RELOAD",
      "events": {},
      "key": "ood.APICaller",
      "path": "dsm.view.config.form.field.datetime.DatePicker.RELOAD",
      "properties": {
        "allform": false,
        "autoRun": true,
        "checkRequired": false,
        "checkValid": false,
        "desc": "日期选择框",
        "id": "/dsm/view/config/form/field/datetime/DatePicker",
        "imageClass": "ri-calendar-line",
        "isAllform": false,
        "methodName": "getDatePicker",
        "name": "DatePicker",
        "proxyType": "auto",
        "queryAsync": true,
        "queryMethod": "POST",
        "queryURL": "/dsm/view/config/form/field/datetime/DatePicker",
        "requestDataSource": [
          {
            "name": "DatePickerMain",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "PAGECTX",
            "path": "",
            "type": "FORM"
          }
        ],
        "requestType": "FORM",
        "responseCallback": [],
        "responseDataTarget": [
          {
            "name": "DatePickerMain",
            "path": "data",
            "type": "FORM"
          },
          {
            "name": "PAGECTX",
            "path": "data",
            "type": "FORM"
          }
        ],
        "responseType": "JSON",
        "sourceClassName": "net.ooder.dsm.view.config.form.field.combo.ComboDateTimeGroup",
        "tabindex": 4,
        "tips": "日期选择框"
      }
    }
  ],
  "className": "dsm.view.config.form.field.datetime.DatePicker",
  "customFunctions": {},
  "desc": "日期选择框",
  "dio": false,
  "events": {},
  "formulas": [],
  "key": "ood.Module",
  "moduleType": "EUClass",
  "moduleVar": {},
  "moduleViewType": "FORMCONFIG",
  "path": "dsm.view.config.form.field.datetime.DatePicker",
  "properties": {
    "autoDestroy": true,
    "bindClass": [],
    "caption": "日期选择框",
    "currComponentAlias": "DatePicker",
    "dock": "fill",
    "title": "日期选择框"
  },
  "reSetUrl": "/dsm/view/config/form/field/combo/date/reSetDatePicker",
  "saveUrl": "/dsm/view/config/form/field/combo/date/updateDatePicker"
}