{
  "alias": "MenuBarConfig",
  "children": [
    {
      "alias": "PAGECTX",
      "children": [
        {
          "alias": "currentClassName",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.menu.menubar.MenuBarConfig.PAGECTX.currentClassName",
          "properties": {
            "formField": true,
            "isPid": true,
            "name": "currentClassName",
            "pid": true,
            "tabindex": 0
          }
        },
        {
          "alias": "xpath",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.menu.menubar.MenuBarConfig.PAGECTX.xpath",
          "properties": {
            "formField": true,
            "isPid": true,
            "name": "xpath",
            "pid": true,
            "tabindex": 1
          }
        },
        {
          "alias": "sourceMethodName",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.menu.menubar.MenuBarConfig.PAGECTX.sourceMethodName",
          "properties": {
            "formField": true,
            "isPid": true,
            "name": "sourceMethodName",
            "pid": true,
            "tabindex": 2
          }
        },
        {
          "alias": "sourceClassName",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.menu.menubar.MenuBarConfig.PAGECTX.sourceClassName",
          "properties": {
            "formField": true,
            "isPid": true,
            "name": "sourceClassName",
            "pid": true,
            "tabindex": 3
          }
        },
        {
          "alias": "projectName",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.menu.menubar.MenuBarConfig.PAGECTX.projectName",
          "properties": {
            "formField": true,
            "isPid": false,
            "name": "projectName",
            "pid": false,
            "tabindex": 4,
            "value": "DSMdsmVVVERSION0"
          }
        },
        {
          "alias": "domainId",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.menu.menubar.MenuBarConfig.PAGECTX.domainId",
          "properties": {
            "formField": true,
            "isPid": true,
            "name": "domainId",
            "pid": true,
            "tabindex": 5
          }
        },
        {
          "alias": "projectVersionName",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.menu.menubar.MenuBarConfig.PAGECTX.projectVersionName",
          "properties": {
            "formField": true,
            "isPid": false,
            "name": "projectVersionName",
            "pid": false,
            "tabindex": 6,
            "value": "DSMdsmVVVERSION0"
          }
        },
        {
          "alias": "parentId",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.menu.menubar.MenuBarConfig.PAGECTX.parentId",
          "properties": {
            "formField": true,
            "isPid": true,
            "name": "parentId",
            "pid": true,
            "tabindex": 7
          }
        },
        {
          "alias": "id",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.menu.menubar.MenuBarConfig.PAGECTX.id",
          "properties": {
            "formField": true,
            "isPid": true,
            "name": "id",
            "pid": true,
            "tabindex": 8
          }
        },
        {
          "alias": "index",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.menu.menubar.MenuBarConfig.PAGECTX.index",
          "properties": {
            "formField": true,
            "isPid": false,
            "name": "index",
            "pid": false,
            "tabindex": 9
          }
        },
        {
          "alias": "iconColors",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.menu.menubar.MenuBarConfig.PAGECTX.iconColors",
          "properties": {
            "formField": true,
            "isPid": false,
            "name": "iconColors",
            "pid": false,
            "tabindex": 10
          }
        },
        {
          "alias": "itemColors",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.menu.menubar.MenuBarConfig.PAGECTX.itemColors",
          "properties": {
            "formField": true,
            "isPid": false,
            "name": "itemColors",
            "pid": false,
            "tabindex": 11
          }
        },
        {
          "alias": "fontColors",
          "events": {},
          "key": "ood.UI.HiddenInput",
          "path": "dsm.view.config.menu.menubar.MenuBarConfig.PAGECTX.fontColors",
          "properties": {
            "formField": true,
            "isPid": false,
            "name": "fontColors",
            "pid": false,
            "tabindex": 12
          }
        }
      ],
      "events": {},
      "key": "ood.UI.Block",
      "params": {},
      "path": "dsm.view.config.menu.menubar.MenuBarConfig.PAGECTX",
      "properties": {
        "borderType": "none",
        "tabindex": 0,
        "visibility": "hidden"
      }
    },
    {
      "alias": "MenuBarConfigMain",
      "children": [
        {
          "alias": "MenuBarConfig",
          "children": [
            {
              "alias": "caption",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.caption",
              "properties": {
                "caption": "显示名称",
                "defaultFocus": false,
                "desc": "显示名称",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "caption",
                "imageClass": "",
                "items": [],
                "labelCaption": "显示名称",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "caption",
                "readonly": false,
                "tabindex": 0,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "B1"
            },
            {
              "alias": "menuType",
              "events": {},
              "key": "ood.UI.ComboInput",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.menuType",
              "properties": {
                "defaultFocus": false,
                "desc": "菜单类型",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "dynLoad": true,
                "enumClass": "net.ooder.esd.annotation.menu.CustomMenuType",
                "items": [
                  {
                    "bindClass": [],
                    "caption": "工具栏",
                    "id": "TOOLBAR",
                    "imageClass": "ri-tools-line",
                    "name": "工具栏",
                    "tabindex": 0,
                    "tagVar": {
                      "name": "TOOLBAR",
                      "clazz": "net.ooder.esd.annotation.menu.CustomMenuType"
                    },
                    "title": "工具栏"
                  },
                  {
                    "bindClass": [],
                    "caption": "弹出菜单",
                    "id": "LISTMENU",
                    "imageClass": "ri-tools-line",
                    "name": "弹出菜单",
                    "tabindex": 1,
                    "tagVar": {
                      "name": "LISTMENU",
                      "clazz": "net.ooder.esd.annotation.menu.CustomMenuType"
                    },
                    "title": "弹出菜单"
                  },
                  {
                    "bindClass": [],
                    "caption": "下标栏",
                    "id": "BOTTOMBAR",
                    "imageClass": "ri-checkbox-blank-line",
                    "name": "下标栏",
                    "tabindex": 2,
                    "tagVar": {
                      "name": "BOTTOMBAR",
                      "clazz": "net.ooder.esd.annotation.menu.CustomMenuType"
                    },
                    "title": "下标栏"
                  },
                  {
                    "bindClass": [],
                    "caption": "菜单栏",
                    "id": "MENUBAR",
                    "imageClass": "ri-menu-line",
                    "name": "菜单栏",
                    "tabindex": 3,
                    "tagVar": {
                      "name": "MENUBAR",
                      "clazz": "net.ooder.esd.annotation.menu.CustomMenuType"
                    },
                    "title": "菜单栏"
                  },
                  {
                    "bindClass": [],
                    "caption": "行控制按钮",
                    "id": "ROWCMD",
                    "imageClass": "ri-checkbox-blank-line",
                    "name": "行控制按钮",
                    "tabindex": 4,
                    "tagVar": {
                      "name": "ROWCMD",
                      "clazz": "net.ooder.esd.annotation.menu.CustomMenuType"
                    },
                    "title": "行控制按钮"
                  },
                  {
                    "bindClass": [],
                    "caption": "右键菜单",
                    "id": "CONTEXTMENU",
                    "imageClass": "ri-menu-line",
                    "name": "右键菜单",
                    "tabindex": 5,
                    "tagVar": {
                      "name": "CONTEXTMENU",
                      "clazz": "net.ooder.esd.annotation.menu.CustomMenuType"
                    },
                    "title": "右键菜单"
                  },
                  {
                    "bindClass": [],
                    "caption": "子菜单",
                    "id": "SUB",
                    "imageClass": "ri-menu-line",
                    "name": "子菜单",
                    "tabindex": 6,
                    "tagVar": {
                      "name": "SUB",
                      "clazz": "net.ooder.esd.annotation.menu.CustomMenuType"
                    },
                    "title": "子菜单"
                  },
                  {
                    "bindClass": [],
                    "caption": "流程控制栏",
                    "id": "BPM",
                    "imageClass": "ri-node-tree",
                    "name": "流程控制栏",
                    "tabindex": 7,
                    "tagVar": {
                      "name": "BPM",
                      "clazz": "net.ooder.esd.annotation.menu.CustomMenuType"
                    },
                    "title": "流程控制栏"
                  },
                  {
                    "bindClass": [],
                    "caption": "流程控制栏",
                    "id": "BPMBOTTOM",
                    "imageClass": "ri-node-tree",
                    "name": "流程控制栏",
                    "tabindex": 8,
                    "tagVar": {
                      "name": "BPMBOTTOM",
                      "clazz": "net.ooder.esd.annotation.menu.CustomMenuType"
                    },
                    "title": "流程控制栏"
                  },
                  {
                    "bindClass": [],
                    "caption": "RAD通用组件",
                    "id": "COMPONENT",
                    "imageClass": "ri-menu-line",
                    "name": "RAD通用组件",
                    "tabindex": 9,
                    "tagVar": {
                      "name": "COMPONENT",
                      "clazz": "net.ooder.esd.annotation.menu.CustomMenuType"
                    },
                    "title": "RAD通用组件"
                  },
                  {
                    "bindClass": [],
                    "caption": "RAD顶部插件",
                    "id": "PLUGINS",
                    "imageClass": "ri-menu-line",
                    "name": "RAD顶部插件",
                    "tabindex": 10,
                    "tagVar": {
                      "name": "PLUGINS",
                      "clazz": "net.ooder.esd.annotation.menu.CustomMenuType"
                    },
                    "title": "RAD顶部插件"
                  },
                  {
                    "bindClass": [],
                    "caption": "RAD工具栏菜单",
                    "id": "TOP",
                    "imageClass": "ri-menu-line",
                    "name": "RAD工具栏菜单",
                    "tabindex": 11,
                    "tagVar": {
                      "name": "TOP",
                      "clazz": "net.ooder.esd.annotation.menu.CustomMenuType"
                    },
                    "title": "RAD工具栏菜单"
                  }
                ],
                "labelCaption": "菜单类型",
                "name": "menuType",
                "readonly": false,
                "tabindex": 1,
                "type": "listbox",
                "visibility": "visible"
              },
              "target": "B2"
            },
            {
              "alias": "dock",
              "events": {},
              "key": "ood.UI.ComboInput",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.dock",
              "properties": {
                "defaultFocus": false,
                "desc": "菜单位置",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "dynLoad": true,
                "enumClass": "net.ooder.esd.annotation.ui.Dock",
                "items": [
                  {
                    "bindClass": [],
                    "caption": "默认",
                    "id": "none",
                    "name": "默认",
                    "tabindex": 0,
                    "tagVar": {
                      "name": "none",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "默认",
                    "type": "none"
                  },
                  {
                    "bindClass": [],
                    "caption": "顶部对齐",
                    "id": "top",
                    "name": "顶部对齐",
                    "tabindex": 1,
                    "tagVar": {
                      "name": "top",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "顶部对齐"
                  },
                  {
                    "bindClass": [],
                    "caption": "底部对齐",
                    "id": "bottom",
                    "name": "底部对齐",
                    "tabindex": 2,
                    "tagVar": {
                      "name": "bottom",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "底部对齐"
                  },
                  {
                    "bindClass": [],
                    "caption": "左对齐",
                    "id": "left",
                    "name": "左对齐",
                    "tabindex": 3,
                    "tagVar": {
                      "name": "left",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "左对齐"
                  },
                  {
                    "bindClass": [],
                    "caption": "右对齐",
                    "id": "right",
                    "name": "右对齐",
                    "tabindex": 4,
                    "tagVar": {
                      "name": "right",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "右对齐"
                  },
                  {
                    "bindClass": [],
                    "caption": "居中对齐",
                    "id": "center",
                    "name": "居中对齐",
                    "tabindex": 5,
                    "tagVar": {
                      "name": "center",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "居中对齐"
                  },
                  {
                    "bindClass": [],
                    "caption": "垂直居中",
                    "id": "middle",
                    "name": "垂直居中",
                    "tabindex": 6,
                    "tagVar": {
                      "name": "middle",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "垂直居中"
                  },
                  {
                    "bindClass": [],
                    "caption": "自适应排列",
                    "id": "origin",
                    "name": "自适应排列",
                    "tabindex": 7,
                    "tagVar": {
                      "name": "origin",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "自适应排列"
                  },
                  {
                    "bindClass": [],
                    "caption": "宽度自适应",
                    "id": "width",
                    "name": "宽度自适应",
                    "tabindex": 8,
                    "tagVar": {
                      "name": "width",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "宽度自适应"
                  },
                  {
                    "bindClass": [],
                    "caption": "高度自适应",
                    "id": "height",
                    "name": "高度自适应",
                    "tabindex": 9,
                    "tagVar": {
                      "name": "height",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "高度自适应"
                  },
                  {
                    "bindClass": [],
                    "caption": "自动填充",
                    "id": "fill",
                    "name": "自动填充",
                    "tabindex": 10,
                    "tagVar": {
                      "name": "fill",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "自动填充"
                  },
                  {
                    "bindClass": [],
                    "caption": "覆盖",
                    "id": "cover",
                    "name": "覆盖",
                    "tabindex": 11,
                    "tagVar": {
                      "name": "cover",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "覆盖"
                  }
                ],
                "labelCaption": "菜单位置",
                "name": "dock",
                "readonly": false,
                "tabindex": 2,
                "type": "listbox",
                "visibility": "visible"
              },
              "target": "D2"
            },
            {
              "alias": "barDock",
              "events": {},
              "key": "ood.UI.ComboInput",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.barDock",
              "properties": {
                "defaultFocus": false,
                "desc": "工具栏布局",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "dynLoad": true,
                "enumClass": "net.ooder.esd.annotation.ui.Dock",
                "items": [
                  {
                    "bindClass": [],
                    "caption": "默认",
                    "id": "none",
                    "name": "默认",
                    "tabindex": 0,
                    "tagVar": {
                      "name": "none",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "默认",
                    "type": "none"
                  },
                  {
                    "bindClass": [],
                    "caption": "顶部对齐",
                    "id": "top",
                    "name": "顶部对齐",
                    "tabindex": 1,
                    "tagVar": {
                      "name": "top",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "顶部对齐"
                  },
                  {
                    "bindClass": [],
                    "caption": "底部对齐",
                    "id": "bottom",
                    "name": "底部对齐",
                    "tabindex": 2,
                    "tagVar": {
                      "name": "bottom",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "底部对齐"
                  },
                  {
                    "bindClass": [],
                    "caption": "左对齐",
                    "id": "left",
                    "name": "左对齐",
                    "tabindex": 3,
                    "tagVar": {
                      "name": "left",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "左对齐"
                  },
                  {
                    "bindClass": [],
                    "caption": "右对齐",
                    "id": "right",
                    "name": "右对齐",
                    "tabindex": 4,
                    "tagVar": {
                      "name": "right",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "右对齐"
                  },
                  {
                    "bindClass": [],
                    "caption": "居中对齐",
                    "id": "center",
                    "name": "居中对齐",
                    "tabindex": 5,
                    "tagVar": {
                      "name": "center",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "居中对齐"
                  },
                  {
                    "bindClass": [],
                    "caption": "垂直居中",
                    "id": "middle",
                    "name": "垂直居中",
                    "tabindex": 6,
                    "tagVar": {
                      "name": "middle",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "垂直居中"
                  },
                  {
                    "bindClass": [],
                    "caption": "自适应排列",
                    "id": "origin",
                    "name": "自适应排列",
                    "tabindex": 7,
                    "tagVar": {
                      "name": "origin",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "自适应排列"
                  },
                  {
                    "bindClass": [],
                    "caption": "宽度自适应",
                    "id": "width",
                    "name": "宽度自适应",
                    "tabindex": 8,
                    "tagVar": {
                      "name": "width",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "宽度自适应"
                  },
                  {
                    "bindClass": [],
                    "caption": "高度自适应",
                    "id": "height",
                    "name": "高度自适应",
                    "tabindex": 9,
                    "tagVar": {
                      "name": "height",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "高度自适应"
                  },
                  {
                    "bindClass": [],
                    "caption": "自动填充",
                    "id": "fill",
                    "name": "自动填充",
                    "tabindex": 10,
                    "tagVar": {
                      "name": "fill",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "自动填充"
                  },
                  {
                    "bindClass": [],
                    "caption": "覆盖",
                    "id": "cover",
                    "name": "覆盖",
                    "tabindex": 11,
                    "tagVar": {
                      "name": "cover",
                      "clazz": "net.ooder.esd.annotation.ui.Dock"
                    },
                    "title": "覆盖"
                  }
                ],
                "labelCaption": "工具栏布局",
                "name": "barDock",
                "readonly": false,
                "tabindex": 3,
                "type": "listbox",
                "visibility": "visible"
              },
              "target": "B3"
            },
            {
              "alias": "imageClass",
              "events": {},
              "key": "ood.UI.ComboInput",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.imageClass",
              "properties": {
                "caption": "图标",
                "defaultFocus": false,
                "desc": "图标",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "id": "imageClass",
                "items": [],
                "labelCaption": "图标",
                "name": "imageClass",
                "readonly": false,
                "tabindex": 4,
                "type": "input",
                "visibility": "visible"
              },
              "target": "D3"
            },
            {
              "alias": "hAlign",
              "events": {},
              "key": "ood.UI.ComboInput",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.hAlign",
              "properties": {
                "caption": "横向对齐",
                "defaultFocus": false,
                "desc": "横向对齐",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "dynLoad": true,
                "enumClass": "net.ooder.esd.annotation.ui.HAlignType",
                "items": [
                  {
                    "bindClass": [],
                    "caption": "center",
                    "id": "center",
                    "tabindex": 0,
                    "tagVar": {
                      "name": "center",
                      "clazz": "net.ooder.esd.annotation.ui.HAlignType"
                    },
                    "title": "center"
                  },
                  {
                    "bindClass": [],
                    "caption": "left",
                    "id": "left",
                    "tabindex": 1,
                    "tagVar": {
                      "name": "left",
                      "clazz": "net.ooder.esd.annotation.ui.HAlignType"
                    },
                    "title": "left"
                  },
                  {
                    "bindClass": [],
                    "caption": "right",
                    "id": "right",
                    "tabindex": 2,
                    "tagVar": {
                      "name": "right",
                      "clazz": "net.ooder.esd.annotation.ui.HAlignType"
                    },
                    "title": "right"
                  }
                ],
                "labelCaption": "横向对齐",
                "name": "hAlign",
                "readonly": false,
                "tabindex": 5,
                "type": "combobox",
                "visibility": "visible"
              },
              "target": "B4"
            },
            {
              "alias": "vAlign",
              "events": {},
              "key": "ood.UI.ComboInput",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.vAlign",
              "properties": {
                "caption": "垂直对齐",
                "defaultFocus": false,
                "desc": "垂直对齐",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "dynLoad": true,
                "enumClass": "net.ooder.esd.annotation.ui.VAlignType",
                "items": [
                  {
                    "bindClass": [],
                    "caption": "bottom",
                    "id": "bottom",
                    "tabindex": 0,
                    "tagVar": {
                      "name": "bottom",
                      "clazz": "net.ooder.esd.annotation.ui.VAlignType"
                    },
                    "title": "bottom"
                  },
                  {
                    "bindClass": [],
                    "caption": "middle",
                    "id": "middle",
                    "tabindex": 1,
                    "tagVar": {
                      "name": "middle",
                      "clazz": "net.ooder.esd.annotation.ui.VAlignType"
                    },
                    "title": "middle"
                  },
                  {
                    "bindClass": [],
                    "caption": "top",
                    "id": "top",
                    "tabindex": 2,
                    "tagVar": {
                      "name": "top",
                      "clazz": "net.ooder.esd.annotation.ui.VAlignType"
                    },
                    "title": "top"
                  }
                ],
                "labelCaption": "垂直对齐",
                "name": "vAlign",
                "readonly": false,
                "tabindex": 6,
                "type": "combobox",
                "visibility": "visible"
              },
              "target": "D4"
            },
            {
              "alias": "showCaption",
              "events": {},
              "key": "ood.UI.CheckBox",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.showCaption",
              "properties": {
                "caption": "",
                "defaultFocus": false,
                "desc": "显示标题",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "dock": "none",
                "events": {},
                "id": "showCaption",
                "name": "showCaption",
                "tabindex": 7,
                "visibility": "visible"
              },
              "target": "B5"
            },
            {
              "alias": "handler",
              "events": {},
              "key": "ood.UI.CheckBox",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.handler",
              "properties": {
                "caption": "",
                "defaultFocus": false,
                "desc": "行头手柄",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "dock": "none",
                "events": {},
                "id": "handler",
                "name": "handler",
                "tabindex": 8,
                "visibility": "visible"
              },
              "target": "D5"
            },
            {
              "alias": "dynLoad",
              "events": {},
              "key": "ood.UI.CheckBox",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.dynLoad",
              "properties": {
                "caption": "",
                "defaultFocus": false,
                "desc": "动态加载",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "dock": "none",
                "events": {},
                "id": "dynLoad",
                "name": "dynLoad",
                "tabindex": 9,
                "visibility": "visible"
              },
              "target": "B6"
            },
            {
              "alias": "lazy",
              "events": {},
              "key": "ood.UI.CheckBox",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.lazy",
              "properties": {
                "caption": "",
                "defaultFocus": false,
                "desc": "延迟加载",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "dock": "none",
                "events": {},
                "id": "lazy",
                "name": "lazy",
                "tabindex": 10,
                "visibility": "visible"
              },
              "target": "D6"
            },
            {
              "alias": "top",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.top",
              "properties": {
                "caption": "上边距",
                "defaultFocus": false,
                "desc": "上边距",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "top",
                "imageClass": "",
                "items": [],
                "labelCaption": "上边距",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "top",
                "readonly": false,
                "tabindex": 11,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "B7"
            },
            {
              "alias": "itemPadding",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.itemPadding",
              "properties": {
                "caption": "菜单项边距",
                "defaultFocus": false,
                "desc": "菜单项边距",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "itemPadding",
                "imageClass": "",
                "items": [],
                "labelCaption": "菜单项边距",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "itemPadding",
                "readonly": false,
                "tabindex": 12,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "D7"
            },
            {
              "alias": "itemMargin",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.itemMargin",
              "properties": {
                "caption": "菜单项间隔",
                "defaultFocus": false,
                "desc": "菜单项间隔",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "itemMargin",
                "imageClass": "",
                "items": [],
                "labelCaption": "菜单项间隔",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "itemMargin",
                "readonly": false,
                "tabindex": 13,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "B8"
            },
            {
              "alias": "itemWidth",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.itemWidth",
              "properties": {
                "caption": "菜单项宽度",
                "defaultFocus": false,
                "desc": "菜单项宽度",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "itemWidth",
                "imageClass": "",
                "items": [],
                "labelCaption": "菜单项宽度",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "itemWidth",
                "readonly": false,
                "tabindex": 14,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "D8"
            },
            {
              "alias": "itemAlign",
              "events": {},
              "key": "ood.UI.ComboInput",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.itemAlign",
              "properties": {
                "caption": "菜单项位置",
                "defaultFocus": false,
                "desc": "菜单项位置",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "dynLoad": true,
                "enumClass": "net.ooder.esd.annotation.ui.AlignType",
                "items": [
                  {
                    "bindClass": [],
                    "caption": "center",
                    "id": "center",
                    "tabindex": 0,
                    "tagVar": {
                      "name": "center",
                      "clazz": "net.ooder.esd.annotation.ui.AlignType"
                    },
                    "title": "center"
                  },
                  {
                    "bindClass": [],
                    "caption": "left",
                    "id": "left",
                    "tabindex": 1,
                    "tagVar": {
                      "name": "left",
                      "clazz": "net.ooder.esd.annotation.ui.AlignType"
                    },
                    "title": "left"
                  },
                  {
                    "bindClass": [],
                    "caption": "right",
                    "id": "right",
                    "tabindex": 2,
                    "tagVar": {
                      "name": "right",
                      "clazz": "net.ooder.esd.annotation.ui.AlignType"
                    },
                    "title": "right"
                  }
                ],
                "labelCaption": "菜单项位置",
                "name": "itemAlign",
                "readonly": false,
                "tabindex": 15,
                "type": "combobox",
                "visibility": "visible"
              },
              "target": "B9"
            },
            {
              "alias": "itemType",
              "events": {},
              "key": "ood.UI.ComboInput",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.itemType",
              "properties": {
                "caption": "菜单项类型",
                "defaultFocus": false,
                "desc": "菜单项类型",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "dynLoad": true,
                "enumClass": "net.ooder.esd.annotation.ui.StatusItemType",
                "items": [
                  {
                    "bindClass": [],
                    "caption": "text",
                    "id": "text",
                    "tabindex": 0,
                    "tagVar": {
                      "name": "text",
                      "clazz": "net.ooder.esd.annotation.ui.StatusItemType"
                    },
                    "title": "text"
                  },
                  {
                    "bindClass": [],
                    "caption": "button",
                    "id": "button",
                    "tabindex": 1,
                    "tagVar": {
                      "name": "button",
                      "clazz": "net.ooder.esd.annotation.ui.StatusItemType"
                    },
                    "title": "button"
                  },
                  {
                    "bindClass": [],
                    "caption": "dropButton",
                    "id": "dropButton",
                    "tabindex": 2,
                    "tagVar": {
                      "name": "dropButton",
                      "clazz": "net.ooder.esd.annotation.ui.StatusItemType"
                    },
                    "title": "dropButton"
                  }
                ],
                "labelCaption": "菜单项类型",
                "name": "itemType",
                "readonly": false,
                "tabindex": 16,
                "type": "combobox",
                "visibility": "visible"
              },
              "target": "D9"
            },
            {
              "alias": "autoIconColor",
              "events": {},
              "key": "ood.UI.CheckBox",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.autoIconColor",
              "properties": {
                "caption": "",
                "defaultFocus": false,
                "desc": "彩色图标",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "dock": "none",
                "events": {},
                "id": "autoIconColor",
                "name": "autoIconColor",
                "tabindex": 17,
                "visibility": "visible"
              },
              "target": "B10"
            },
            {
              "alias": "autoItemColor",
              "events": {},
              "key": "ood.UI.CheckBox",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.autoItemColor",
              "properties": {
                "caption": "",
                "defaultFocus": false,
                "desc": "彩色选项",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "dock": "none",
                "events": {},
                "id": "autoItemColor",
                "name": "autoItemColor",
                "tabindex": 18,
                "visibility": "visible"
              },
              "target": "D10"
            },
            {
              "alias": "autoFontColor",
              "events": {},
              "key": "ood.UI.CheckBox",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.autoFontColor",
              "properties": {
                "caption": "",
                "defaultFocus": false,
                "desc": "彩色字体",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "dock": "none",
                "events": {},
                "id": "autoFontColor",
                "name": "autoFontColor",
                "tabindex": 19,
                "visibility": "visible"
              },
              "target": "B11"
            },
            {
              "alias": "connected",
              "events": {},
              "key": "ood.UI.CheckBox",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.connected",
              "properties": {
                "caption": "",
                "defaultFocus": false,
                "desc": "自动连接",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "dock": "none",
                "events": {},
                "id": "connected",
                "name": "connected",
                "tabindex": 20,
                "visibility": "visible"
              },
              "target": "D11"
            },
            {
              "alias": "itemHeight",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.itemHeight",
              "properties": {
                "caption": "工具栏高",
                "defaultFocus": false,
                "desc": "工具栏高",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "itemHeight",
                "imageClass": "",
                "items": [],
                "labelCaption": "工具栏高",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "itemHeight",
                "readonly": false,
                "tabindex": 21,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "B12"
            },
            {
              "alias": "width",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.width",
              "properties": {
                "caption": "宽度",
                "defaultFocus": false,
                "desc": "宽度",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "width",
                "imageClass": "",
                "items": [],
                "labelCaption": "宽度",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "width",
                "readonly": false,
                "tabindex": 22,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "D12"
            },
            {
              "alias": "height",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.height",
              "properties": {
                "caption": "高度",
                "defaultFocus": false,
                "desc": "高度",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "height",
                "imageClass": "",
                "items": [],
                "labelCaption": "高度",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "height",
                "readonly": false,
                "tabindex": 23,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "B13"
            },
            {
              "alias": "barheight",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.barheight",
              "properties": {
                "caption": "工具栏高",
                "defaultFocus": false,
                "desc": "工具栏高",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "barheight",
                "imageClass": "",
                "items": [],
                "labelCaption": "工具栏高",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "barheight",
                "readonly": false,
                "tabindex": 24,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "D13"
            },
            {
              "alias": "borderType",
              "events": {},
              "key": "ood.UI.ComboInput",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.borderType",
              "properties": {
                "caption": "边框",
                "defaultFocus": false,
                "desc": "边框",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "dynLoad": true,
                "enumClass": "net.ooder.esd.annotation.ui.BorderType",
                "items": [
                  {
                    "bindClass": [],
                    "caption": "none",
                    "id": "none",
                    "tabindex": 0,
                    "tagVar": {
                      "name": "none",
                      "clazz": "net.ooder.esd.annotation.ui.BorderType"
                    },
                    "title": "none"
                  },
                  {
                    "bindClass": [],
                    "caption": "flat",
                    "id": "flat",
                    "tabindex": 1,
                    "tagVar": {
                      "name": "flat",
                      "clazz": "net.ooder.esd.annotation.ui.BorderType"
                    },
                    "title": "flat"
                  },
                  {
                    "bindClass": [],
                    "caption": "inset",
                    "id": "inset",
                    "tabindex": 2,
                    "tagVar": {
                      "name": "inset",
                      "clazz": "net.ooder.esd.annotation.ui.BorderType"
                    },
                    "title": "inset"
                  },
                  {
                    "bindClass": [],
                    "caption": "outset",
                    "id": "outset",
                    "tabindex": 3,
                    "tagVar": {
                      "name": "outset",
                      "clazz": "net.ooder.esd.annotation.ui.BorderType"
                    },
                    "title": "outset"
                  }
                ],
                "labelCaption": "边框",
                "name": "borderType",
                "readonly": false,
                "tabindex": 25,
                "type": "combobox",
                "visibility": "visible"
              },
              "target": "B14"
            },
            {
              "alias": "barBorderType",
              "events": {},
              "key": "ood.UI.ComboInput",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.barBorderType",
              "properties": {
                "caption": "工具栏边框",
                "defaultFocus": false,
                "desc": "工具栏边框",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "dynLoad": true,
                "enumClass": "net.ooder.esd.annotation.ui.BorderType",
                "items": [
                  {
                    "bindClass": [],
                    "caption": "none",
                    "id": "none",
                    "tabindex": 0,
                    "tagVar": {
                      "name": "none",
                      "clazz": "net.ooder.esd.annotation.ui.BorderType"
                    },
                    "title": "none"
                  },
                  {
                    "bindClass": [],
                    "caption": "flat",
                    "id": "flat",
                    "tabindex": 1,
                    "tagVar": {
                      "name": "flat",
                      "clazz": "net.ooder.esd.annotation.ui.BorderType"
                    },
                    "title": "flat"
                  },
                  {
                    "bindClass": [],
                    "caption": "inset",
                    "id": "inset",
                    "tabindex": 2,
                    "tagVar": {
                      "name": "inset",
                      "clazz": "net.ooder.esd.annotation.ui.BorderType"
                    },
                    "title": "inset"
                  },
                  {
                    "bindClass": [],
                    "caption": "outset",
                    "id": "outset",
                    "tabindex": 3,
                    "tagVar": {
                      "name": "outset",
                      "clazz": "net.ooder.esd.annotation.ui.BorderType"
                    },
                    "title": "outset"
                  }
                ],
                "labelCaption": "工具栏边框",
                "name": "barBorderType",
                "readonly": false,
                "tabindex": 26,
                "type": "combobox",
                "visibility": "visible"
              },
              "target": "D14"
            },
            {
              "alias": "tagCmdsAlign",
              "events": {},
              "key": "ood.UI.ComboInput",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.tagCmdsAlign",
              "properties": {
                "caption": "按钮位置",
                "defaultFocus": false,
                "desc": "按钮位置",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "dynLoad": true,
                "enumClass": "net.ooder.esd.annotation.ui.TagCmdsAlign",
                "items": [
                  {
                    "bindClass": [],
                    "caption": "left",
                    "id": "left",
                    "tabindex": 0,
                    "tagVar": {
                      "name": "left",
                      "clazz": "net.ooder.esd.annotation.ui.TagCmdsAlign"
                    },
                    "title": "left"
                  },
                  {
                    "bindClass": [],
                    "caption": "right",
                    "id": "right",
                    "tabindex": 1,
                    "tagVar": {
                      "name": "right",
                      "clazz": "net.ooder.esd.annotation.ui.TagCmdsAlign"
                    },
                    "title": "right"
                  },
                  {
                    "bindClass": [],
                    "caption": "floatright",
                    "id": "floatright",
                    "tabindex": 2,
                    "tagVar": {
                      "name": "floatright",
                      "clazz": "net.ooder.esd.annotation.ui.TagCmdsAlign"
                    },
                    "title": "floatright"
                  }
                ],
                "labelCaption": "按钮位置",
                "name": "tagCmdsAlign",
                "readonly": false,
                "tabindex": 27,
                "type": "combobox",
                "visibility": "visible"
              },
              "target": "B15"
            },
            {
              "alias": "menus",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.menus",
              "properties": {
                "caption": "menus",
                "defaultFocus": false,
                "desc": "menus",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "menus",
                "items": [],
                "labelCaption": "menus",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "menus",
                "readonly": false,
                "tabindex": 28,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "D15"
            },
            {
              "alias": "menuClasses",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.menuClasses",
              "properties": {
                "caption": "menuClasses",
                "defaultFocus": false,
                "desc": "menuClasses",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "menuClasses",
                "items": [],
                "labelCaption": "menuClasses",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "menuClasses",
                "readonly": false,
                "tabindex": 29,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "B16"
            },
            {
              "alias": "serviceClass",
              "events": {},
              "key": "ood.UI.Input",
              "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig.serviceClass",
              "properties": {
                "caption": "实现类",
                "defaultFocus": false,
                "desc": "实现类",
                "disableClickEffect": false,
                "disableHoverEffect": false,
                "disableTips": false,
                "disabled": false,
                "dock": "none",
                "events": {},
                "id": "serviceClass",
                "imageClass": "",
                "items": [],
                "labelCaption": "实现类",
                "labelPos": "left",
                "labelSize": "6.0em",
                "name": "serviceClass",
                "readonly": false,
                "tabindex": 30,
                "tagVar": {},
                "visibility": "visible"
              },
              "target": "B17"
            }
          ],
          "events": {},
          "key": "ood.UI.FormLayout",
          "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain.MenuBarConfig",
          "properties": {
            "caption": "基础信息",
            "defaultColWidth": 150,
            "defaultColumnSize": -1,
            "defaultFocus": false,
            "defaultRowHeight": 35,
            "defaultRowSize": -1,
            "disableClickEffect": false,
            "disableHoverEffect": false,
            "disableTips": false,
            "disabled": false,
            "dock": "fill",
            "floatHandler": false,
            "id": "menuBarConfig",
            "imageClass": "ri-file-text-line",
            "layoutData": {
              "cells": {
                "C2": {
                  "cellName": "C2",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "菜单位置"
                },
                "A1": {
                  "cellName": "A1",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "显示名称"
                },
                "C3": {
                  "cellName": "C3",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "图标"
                },
                "A2": {
                  "cellName": "A2",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "菜单类型"
                },
                "C4": {
                  "cellName": "C4",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "垂直对齐"
                },
                "A3": {
                  "cellName": "A3",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "工具栏布局"
                },
                "C5": {
                  "cellName": "C5",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "行头手柄"
                },
                "A4": {
                  "cellName": "A4",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "横向对齐"
                },
                "C6": {
                  "cellName": "C6",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "延迟加载"
                },
                "A5": {
                  "cellName": "A5",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "显示标题"
                },
                "C7": {
                  "cellName": "C7",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "菜单项边距"
                },
                "A6": {
                  "cellName": "A6",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "动态加载"
                },
                "C8": {
                  "cellName": "C8",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "菜单项宽度"
                },
                "A7": {
                  "cellName": "A7",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "上边距"
                },
                "C9": {
                  "cellName": "C9",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "菜单项类型"
                },
                "A8": {
                  "cellName": "A8",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "菜单项间隔"
                },
                "A9": {
                  "cellName": "A9",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "菜单项位置"
                },
                "A10": {
                  "cellName": "A10",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "彩色图标"
                },
                "A11": {
                  "cellName": "A11",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "彩色字体"
                },
                "C11": {
                  "cellName": "C11",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "自动连接"
                },
                "A12": {
                  "cellName": "A12",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "工具栏高"
                },
                "C10": {
                  "cellName": "C10",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "彩色选项"
                },
                "A13": {
                  "cellName": "A13",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "高度"
                },
                "C13": {
                  "cellName": "C13",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "工具栏高"
                },
                "A14": {
                  "cellName": "A14",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "边框"
                },
                "C12": {
                  "cellName": "C12",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "宽度"
                },
                "A15": {
                  "cellName": "A15",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "按钮位置"
                },
                "C15": {
                  "cellName": "C15",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "menus"
                },
                "A16": {
                  "cellName": "A16",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "menuClasses"
                },
                "C14": {
                  "cellName": "C14",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "工具栏边框"
                },
                "A17": {
                  "cellName": "A17",
                  "style": {
                    "textAlign": "center"
                  },
                  "value": "实现类"
                }
              },
              "colSetting": {
                "A": {
                  "manualWidth": 150
                },
                "B": {
                  "manualWidth": 150
                },
                "C": {
                  "manualWidth": 150
                },
                "D": {
                  "manualWidth": 150
                }
              },
              "cols": 4,
              "merged": [
                {
                  "col": 1,
                  "colspan": 3,
                  "removed": false,
                  "row": 0,
                  "rowspan": 1
                },
                {
                  "col": 1,
                  "colspan": 3,
                  "removed": false,
                  "row": 16,
                  "rowspan": 1
                }
              ],
              "rowSetting": {
                "1": {
                  "manualHeight": 35
                },
                "2": {
                  "manualHeight": 35
                },
                "3": {
                  "manualHeight": 35
                },
                "4": {
                  "manualHeight": 35
                },
                "5": {
                  "manualHeight": 35
                },
                "6": {
                  "manualHeight": 35
                },
                "7": {
                  "manualHeight": 35
                },
                "8": {
                  "manualHeight": 35
                },
                "9": {
                  "manualHeight": 35
                },
                "10": {
                  "manualHeight": 35
                },
                "11": {
                  "manualHeight": 35
                },
                "12": {
                  "manualHeight": 35
                },
                "13": {
                  "manualHeight": 35
                },
                "14": {
                  "manualHeight": 35
                },
                "15": {
                  "manualHeight": 35
                },
                "16": {
                  "manualHeight": 35
                },
                "17": {
                  "manualHeight": 35
                }
              },
              "rows": 17
            },
            "lineSpacing": 10,
            "mode": "write",
            "name": "GetMenuBarConfig",
            "solidGridlines": true,
            "stretchH": "all",
            "stretchHeight": "none",
            "tabindex": 0,
            "tagVar": {},
            "visibility": "visible"
          }
        }
      ],
      "events": {},
      "key": "ood.UI.Block",
      "path": "dsm.view.config.menu.menubar.MenuBarConfig.MenuBarConfigMain",
      "properties": {
        "dock": "fill",
        "panelBgClr": "transparent",
        "tabindex": 1
      }
    },
    {
      "alias": "SAVE",
      "events": {},
      "key": "ood.APICaller",
      "path": "dsm.view.config.menu.menubar.MenuBarConfig.SAVE",
      "properties": {
        "allform": false,
        "autoRun": false,
        "checkRequired": false,
        "checkValid": false,
        "desc": "保存",
        "id": "/dsm/view/config/menu/menubar/saveMenuBarInfo",
        "imageClass": "ri-code-box-line",
        "isAllform": false,
        "methodName": "saveMenuBarInfo",
        "name": "saveMenuBarInfo",
        "proxyType": "auto",
        "queryAsync": true,
        "queryMethod": "POST",
        "queryURL": "/dsm/view/config/menu/menubar/saveMenuBarInfo",
        "requestDataSource": [
          {
            "name": "menuConfigView",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "projectName",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "FieldMenuClass",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "PAGECTX",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "menuConfigView",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "projectName",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "MenuBarConfigMain",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "PAGECTX",
            "path": "",
            "type": "FORM"
          }
        ],
        "requestType": "JSON",
        "responseCallback": [],
        "responseDataTarget": [],
        "responseType": "JSON",
        "sourceClassName": "net.ooder.dsm.view.config.menu.menubar.MenuBarConfigService",
        "tabindex": 2,
        "tips": "保存"
      }
    },
    {
      "alias": "RELOAD",
      "events": {},
      "key": "ood.APICaller",
      "path": "dsm.view.config.menu.menubar.MenuBarConfig.RELOAD",
      "properties": {
        "allform": false,
        "autoRun": true,
        "checkRequired": false,
        "checkValid": false,
        "desc": "基础信息",
        "id": "/dsm/view/config/menu/menubar/MenuBarConfig",
        "imageClass": "ri-code-box-line",
        "isAllform": false,
        "methodName": "getMenuBarConfig",
        "name": "MenuBarConfig",
        "proxyType": "auto",
        "queryAsync": true,
        "queryMethod": "POST",
        "queryURL": "/dsm/view/config/menu/menubar/MenuBarConfig",
        "requestDataSource": [
          {
            "name": "MenuBarConfigMain",
            "path": "",
            "type": "FORM"
          },
          {
            "name": "PAGECTX",
            "path": "",
            "type": "FORM"
          }
        ],
        "requestType": "FORM",
        "responseCallback": [],
        "responseDataTarget": [
          {
            "name": "MenuBarConfigMain",
            "path": "data",
            "type": "FORM"
          },
          {
            "name": "PAGECTX",
            "path": "data",
            "type": "FORM"
          }
        ],
        "responseType": "JSON",
        "sourceClassName": "net.ooder.dsm.view.config.menu.menubar.MenuBarNav",
        "tabindex": 3,
        "tips": "基础信息"
      }
    }
  ],
  "className": "dsm.view.config.menu.menubar.MenuBarConfig",
  "customFunctions": {},
  "desc": "基础信息",
  "dio": false,
  "events": {},
  "formulas": [],
  "key": "ood.Module",
  "moduleType": "EUClass",
  "moduleVar": {},
  "moduleViewType": "FORMCONFIG",
  "path": "dsm.view.config.menu.menubar.MenuBarConfig",
  "properties": {
    "autoDestroy": true,
    "bindClass": [],
    "caption": "基础信息",
    "currComponentAlias": "MenuBarConfig",
    "dock": "fill",
    "title": "基础信息"
  },
  "saveUrl": "/dsm/view/config/menu/menubar/saveMenuBarInfo"
}